"""empty message

Revision ID: 33d328ac81c1
Revises: 863d0cd90682
Create Date: 2021-10-24 16:32:55.930060

"""
from alembic import op
import sqlalchemy as sa
import os

environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '33d328ac81c1'
down_revision = '863d0cd90682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('cover_img_url', sa.String(length=1000), nullable=False))
    if environment == "production":
        op.execute(f"ALTER TABLE products SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'cover_img_url')
    # ### end Alembic commands ###
