"""empty message

Revision ID: 775e012ff930
Revises: aec5fed925b3
Create Date: 2021-10-27 01:02:16.298629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775e012ff930'
down_revision = 'aec5fed925b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('username', sa.String(length=40), nullable=False))
    op.add_column('reviews', sa.Column('rating', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'rating')
    op.drop_column('reviews', 'username')
    # ### end Alembic commands ###
