"""empty message

Revision ID: aec5fed925b3
Revises: 33d328ac81c1
Create Date: 2021-10-25 01:57:22.651626

"""
from alembic import op
import sqlalchemy as sa
import os

environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = 'aec5fed925b3'
down_revision = '33d328ac81c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity_in_cart', sa.Integer(), nullable=False))
    if environment == "production":
        op.execute(f"ALTER TABLE products SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'quantity_in_cart')
    # ### end Alembic commands ###
